source("https://jonsmitchell.com/code/fxn05.R")
Pop1<- simPop(Popsize = 50, nGenerations = 100, initial_p =0.5, h=1, s=0)
plot(1:nrow(Pop1), Pop1[,1], ylim=c(0,1), type="l", xlab="generation", ylab="allele freq.", lwd=2)
lines(1:nrow(Pop1), Pop1[,2], lwd=2 , col='red')
legend("topleft", legend =c("a","b"), col=c("black", "red"), lwd= 2, bty= "n")
plotFit( nruns=10, n=50, ngens=100, init_p=0.5, h=1,s=0)
Expectation<- c(10,10,10,10)
Observed<- c(15,15,5,5)
Chisq<- sum((Expectation-Observed) ^ 2/Expectation)
barplot(rbind(Expectation, Observed), beside = T, main = bquote(chi^2 ~ "=" ~. (Chisq)), legend.text=c("expected", "observed"))
Expectation<- c(5,0,0,35)
Observed<- c(2,3,10,30)
Chisq<- sum(((Expectation-Observed) ^ 2)/Expectation)
barplot(rbind(Expectation, Observed), beside = T, main = bquote(chi^2 ~ "=" ~. (Chisq)), legend.text=c("expected", "observed"))
Expectation<- c(9,3,3,1)
Observed<- c(20,5,8,2)
Chisq<- sum(((Expectation-Observed) ^ 2)/Expectation)
barplot(rbind(Expectation, Observed), beside = T, main = bquote(chi^2 ~ "=" ~. (Chisq)), legend.text=c("expected", "observed"))


results<- read.csv("https://jonsmitchell.com/data/biol112labresults.csv", stringsAsFactors=F)
counts<- results[,c("yellow", "red", "green", "blue", "black", "tan")]
backgrounds<- c("White", "Red", "Yellow", "Green", "Blue", "Black")
backgrounds<- c("white", "#d53e4f", "#fee08b", "#abdda4", "#3288bd", "black")
calcChi(counts[1,])
Chisqs<- apply(counts, 1, calcChi)
plotChis(counts)
Avg<- mean(Chisqs)
backgroundAvgs<- tapply(Chisqs, results[,3], mean)
propSig<- length( which( Chisqs > 11.70))/length(Chisqs)
percSig<- round(100 * propSig)
head(percSig)
head(propSig)
par(las=1, mar=c(4,4,1,1), mgp=c(2,0.5,0), tck= -0.01, cex.axis =1)
hist(Chisqs, main="", xlab ="chi-squared values", ylab="frequency")
par(las =1, mar= c(4,4,1,1), mgp=c(2,0.5,0), tck= -0.01, cex.axis =1)
plot(1,1, xlim=c(0, 400), ylim=c(1, 8.5), xlab="", ylab="", type="n", yaxt="n")
axis(2, at= 1:length(backgrounds), labels = backgrounds)
mtext(side=1, expression(chi^2), cex=1.75, line=2.5)
counter<-1
for (i in backgrounds) {
Data<- Chisqs[which(results[,3] == i)]
addHist(Y=counter, Dat=Data, Color=backgroundCol[counter])
counter<- counter + 1 
}
dev.off()
