write.csv(data2, 'rawdata.csv', quote=F)
data2
Mass<- which(data2[,9] == 'trait_mass')
cyrusMass <- data2[Mass,]
head(cyrusMass)
Mass<-which(data2[,'event'] == 'trait_mass')
Mass <-which(data2$event == 'trait_mass')
dayID<- apply(data2, 1, function(x) paste(x[1:3], collapse='-'))
dateID<- sapply(dayID, as.Date, format= "%Y-%m-%d", origin = "2022-04-12")
data2$age<- dateID - dateID[which(data2$event == 'birth')]
head(data2)
cyrus2<- data2
cyrus3<- cyrus2[order(cyrus2$age),]
write.csv(cyrus3, 'cyrus_new.csv', quote=F, row.names=FALSE)
Mass<- which(cyrus3$event == 'trait_mass')
cor(cyrus3$value[Mass],cyrus3$age[Mass])
cor.test(cyrus3$value[Mass],cyrus3$age[Mass])
cyrusCor<- cor.test(cyrus3$value[Mass],cyrus3$age[Mass])
summary(cyrusCor)
cyrusANOVA<- aov(cyrus3$value[Mass] ~ cyrus3$age[Mass])
boxplot( cyrus3$value[Mass] ~ cyrus3$age[Mass], xlab="age in days", ylab="mass in kg")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
abline(h=mean(totalMass), lty=2, col='red')
pdf('r02b-BerenAgeVsMass.pdf', height = 4, width = 4)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
boxplot(cyrus3$value[Mass], cyrus3$age[Mass], xlab="age in days", ylab='mass in kg')
boxplot(beren3$value[Mass],beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab="mass in kg")
points(cyrus3$value[Mass]~cyrus3$age[Mass],pch=17,col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs Mass", xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
head(data2)
Mass<- which(data2[,9] == 'trait_mass')
points(beren3$value[Mass]~beren3$age[Mass],pch=16,xlab"age in days",ylab="mass in kg")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
data1
length(data1)
nrow(data1)
ncol(data1)
colnames(data1)
head(data1)
data1[1,]
data1[2,]
data1[1:3,]
beren2<-data1
beren3 <- beren2[order(beren2$age),]
write.csv(beren3, 'beren_new.csv',quote=F, row.names=FALSE)
Mass<-which(beren3$event == "trait_mass")
avgMass<- mean(beren3$value[Mass])
avgMass<- tapply(beren3$value[Mass], beren3$age[Mass], mean)
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
varMass<-tapply(beren3$value[Mass], beren3$age[Mass],var)
totalMass<- tapply(beren3$value[Mass], beren3$age[Mass], sum)
numMass<- tapply(beren3$value[Mass], beren3$age[Mass], length)
cor(beren3$value[Mass], beren3$age[Mass])
cor.test(beren3$value[Mass], beren3$age[Mass])
summary(berenCor)
berenANOVA<- aov(beren3$value[Mass] ~ beren3$age[Mass])
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
abline(h=mean(totalMass), lty=2, col='red')
pdf('r02b-BerenAgeVsMass.pdf', height = 4, width = 4)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
dev.off()
dev.off()
data1
length(data1)
nrow(data1)
ncol(data1)
colnames(data1)
head(data1)
data1[1,]
data1[2,]
data1[1:3,]
data1[1:3, 4]
beren2<-data1
beren3 <- beren2[order(beren2$age),]
write.csv(beren3, 'beren_new.csv',quote=F, row.names=FALSE)
Mass<-which(beren3$event == "trait_mass")
avgMass<- mean(beren3$value[Mass])
avgMass<- tapply(beren3$value[Mass], beren3$age[Mass], mean)
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
varMass<-tapply(beren3$value[Mass], beren3$age[Mass],var)
totalMass<- tapply(beren3$value[Mass], beren3$age[Mass], sum)
numMass<- tapply(beren3$value[Mass], beren3$age[Mass], length)
cor(beren3$value[Mass], beren3$age[Mass])
cor.test(beren3$value[Mass], beren3$age[Mass])
summary(berenCor)
berenANOVA<- aov(beren3$value[Mass] ~ beren3$age[Mass])
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
abline(h=mean(totalMass), lty=2, col='red')
pdf('r02b-BerenAgeVsMass.pdf', height = 4, width = 4)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab="mass in kg")
dev.off()
dev.off()
dev.off()
data1
length(data1)
nrow(data1)
ncol(data1)
colnames(data1)
head(data1)
data1[1,]
data1[2,]
data1[1:3,]
data1[1:3, 4]
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
abline(h=mean(totalMass), lty=2, col='red')
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab="mass in kg")
points(cyrus3$value[Mass]~cyrus3$age[Mass],pch=17,col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs Mass", xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
title("Beren and Cyrus Age Vs Mass", xlab="age in days", ylab="mass in kg")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( cyrus3$value[cMass] ~ cyrus3$age[cMass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
CyrusAgeVsMass<- plot(as.numeric(names(totalcMass)), totalcMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab="mass in kg")
cyrus2<- data2
cyrus3<- cyrus2[order(cyrus2$age),]
write.csv(cyrus3, 'cyrus_new.csv', quote=F, row.names=FALSE)
cMass<- which(cyrus3$event == 'trait_mass')
avgcMass<- mean(cyrus3$value[cMass])
avgcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], mean)
varcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], var)
totalcMass<- tapply(cyrus3$value[cMass],cyrus3$age[cMass], sum)
numcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], length)
cor(cyrus3$value[cMass],cyrus3$age[cMass])
cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
cyrusCor<- cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
summary(cyrusCor)
cyrusANOVA<- aov(cyrus3$value[cMass] ~ cyrus3$age[cMass])
boxplot( cyrus3$value[cMass] ~ cyrus3$age[cMass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
CyrusAgeVsMass<- plot(as.numeric(names(totalcMass)), totalcMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab = "mass in kg")
points(cyrus3$value[cMass]~cyrus3$age[cMass], pch=17, col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs. Mass")
abline(h=mean(totalMass), lty=2, col='red')
pdf('r02b-BerenAgeVsMass.pdf', height = 4, width = 4)
x<-beren3$value[Mass]
y<-beren3$age[Mass]
x2<-cyrus3$value[Mass]
y2<-cyrus3$age[Mass]
plot(x,y, cex=1, pch=16, xlab="Age in Days", ylab="Mass in KG", col="pink")
points(x2, y2, cex=1, pch=16, col="green")
cyrus3$value[Mass]
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
dev.off()
dev.off()
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$value[cMass],cyrus3$age[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[cMass],cyrus3$age[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
boxplot(cyrus3$value[cMass], cyrus3$age[cMass], xlab="age in days", ylab='mass in kg')
boxplot(beren3$value[Mass],beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab="mass in kg")
points(cyrus3$value[Mass]~cyrus3$age[Mass],pch=17,col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs Mass", xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
head(data2)
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
data2[1,]
data2[2,]
data2[1:3,]
data2[1:3, 4]
data2[1:5, 1:3]
cMass<- which(data2[,9] == 'trait_mass')
cyruscMass <- data2[cMass,]
head(cyruscMass)
Mass<-which(data2[,'event'] == 'trait_mass')
Mass <-which(data2$event == 'trait_mass')
dayID<- apply(data2, 1, function(x) paste(x[1:3], collapse='-'))
dateID<- sapply(dayID, as.Date, format= "%Y-%m-%d", origin = "2022-04-12")
data2$age<- dateID - dateID[which(data2$event == 'birth')]
head(data2)
cyrus2<- data2
cyrus3<- cyrus2[order(cyrus2$age),]
write.csv(cyrus3, 'cyrus_new.csv', quote=F, row.names=FALSE)
cMass<- which(cyrus3$event == 'trait_mass')
avgcMass<- mean(cyrus3$value[cMass])
avgcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], mean)
varcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], var)
totalcMass<- tapply(cyrus3$value[cMass],cyrus3$age[cMass], sum)
numcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], length)
cor(cyrus3$value[cMass],cyrus3$age[cMass])
cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
cyrusCor<- cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
summary(cyrusCor)
cyrusANOVA<- aov(cyrus3$value[cMass] ~ cyrus3$age[cMass])
boxplot( cyrus3$value[cMass] ~ cyrus3$age[cMass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
CyrusAgeVsMass<- plot(as.numeric(names(totalcMass)), totalcMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
abline(h=mean(totalcMass), lty=2, col='red')
pdf('r02b-CyrusAgeVsMass.pdf', height = 4, width = 4)
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalcMass)), totalcMass, type="b", pch=16, xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
dev.off()
dev.on()
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot(beren3$value[Mass],beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab="mass in kg")
points(cyrus3$value[cMass]~cyrus3$age[cMass],pch=17,col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs Mass", xlab="age in days", ylab="mass in kg")
abline(h=mean(totalMass), lty=2, col="red")
head(data2)
Mass<- which(data2[,9] == 'trait_mass')
points(beren3$value[Mass]~beren3$age[Mass],pch=16,xlab"age in days",ylab="mass in kg")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
setwd('~/Desktop/Evolution/Tasks/Task_02')
data1<-read.csv('http://jonsmitchell.com/data/beren.csv', stringsAsFactors=F)
setwd('~/Desktop/Evolution/Tasks/Task_02'))
setwd('~/Desktop/Evolution/Tasks/Task_02')
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$value[cMass],cyrus3$age[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$value[cMass],cyrus3$age[cMass], pch=16, col="green")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
cMass<- which(data2[,9] == 'trait_mass')
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab = "mass in kg")
points(cyrus3$value[cMass]~cyrus3$age[cMass], pch=17, col="green", xlab="age in days", ylab="mass in kg")
title("Beren and Cyrus Age Vs. Mass")
abline(h=mean(totalMass), lty=2, col='red')
pdf('r02b-BerenAgeVsMass.pdf', height = 4, width = 4)
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
dev.off()
dev.off()
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$value[Mass],cyrus3$age[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$age[Mass],cyrus3$value[Mass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$age[Mass],cyrus3$value[Mass], pch=16, col="green")
boxplot( beren3$value[Mass] ~ beren3$age[Mass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$age[cMass]~cyrus3$value[cMass], pch=17, col="green", xlab="age in days", ylab="mass in kg")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$age[cMass]~cyrus3$value[cMass], pch=16, col="green", xlab="age in days", ylab="mass in kg")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
points(cyrus3$age[cMass]~cyrus3$value[cMass], pch=16, col="green", xlab="age in days", ylab="mass in kg")
plot(as.numeric(names(totalMass)), totalMass, type="b", col="pink", pch=16, xlab="age in days", ylab = "mass in kg")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$age[cMass],cyrus3$value[cMass], pch=16, col="green")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
points(cyrus3$age[Mass],cyrus3$value[Mass], pch=16, col="green")
points(cyrus3$age[cMass],cyrus3$value[cMass]/1000, pch=16, col="green")
points(cyrus3$age[cMass],cyrus3$value[cMass]/1000, pch=16, col="green", type="b")
cyrus3$value[cMass]
cMass<- which(cyrus3$event == 'trait_mass')
avgcMass<- mean(cyrus3$value[cMass])
avgcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], mean)
varcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], var)
totalcMass<- tapply(cyrus3$value[cMass],cyrus3$age[cMass], sum)
numcMass<-tapply(cyrus3$value[cMass], cyrus3$age[cMass], length)
cor(cyrus3$value[cMass],cyrus3$age[cMass])
cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
cyrusCor<- cor.test(cyrus3$value[cMass],cyrus3$age[cMass])
summary(cyrusCor)
cyrusANOVA<- aov(cyrus3$value[cMass] ~ cyrus3$age[cMass])
boxplot( cyrus3$value[cMass] ~ cyrus3$age[cMass], xlab="age in days", ylab="mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
CyrusAgeVsMass<- plot(as.numeric(names(totalcMass)), totalcMass, type="b", pch=16, xlab="age in days", ylab = "mass in kg")
par(las=1, mar=c(5,5,1,1), mgp=c(2,0.5,0), tck=-0.01)
plot(as.numeric(names(totalMass)), totalMass, type="b", pch=16, xlab="Age in days", ylab = "Mass in kg", col="pink")
points(cyrus3$age[cMass],cyrus3$value[cMass]/1000, pch=16, col="green", type="b")
title("Beren and Cyrus Age Vs. Mass")
legend(1000, 6, legend=c("Beren", "Cyrus"), col=c("pink", "green"), lty=1:1, cex=0.8,title="Kids", text.font=4,bg="yellow")
